# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[6.29147980e-01, 6.06404205e-01, 1.88141032e-01],
       [1.26149489e-02, 5.16384408e-01, 2.84904055e-01],
       [7.41433480e-01, 3.38824753e-01, 8.88956404e-01],
       [5.62906682e-01, 3.26042026e-01, 6.63232583e-01],
       [4.27731985e-01, 2.58430836e-01, 2.03435285e-01],
       [8.56002964e-01, 9.74937992e-02, 1.63879425e-01],
       [1.83413083e-01, 7.85274616e-01, 5.22590376e-01],
       [1.08497479e-01, 8.40478007e-01, 5.11016484e-01],
       [6.46451183e-01, 6.19757354e-01, 5.29945925e-01],
       [7.80874043e-01, 5.21973134e-02, 1.71662529e-01],
       [6.59423402e-01, 1.69502919e-01, 8.33304614e-02],
       [3.56848606e-01, 1.16374844e-01, 2.30458097e-01],
       [5.84120109e-01, 8.40197797e-01, 9.72455374e-01],
       [9.16082529e-01, 2.33083741e-01, 6.75067566e-01],
       [9.95222781e-01, 6.29975622e-01, 3.92362489e-01],
       [1.34723208e-01, 5.38025756e-01, 1.15284999e-01],
       [5.83957662e-02, 5.37907566e-01, 1.33294137e-01],
       [9.46400776e-01, 1.64623

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.85216602, 0.59405298, 0.53621741],
       [0.35684861, 0.11637484, 0.2304581 ]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
clusters = vq(data, clust_centers)
clusters

(array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 1], dtype=int32),
 array([0.413578  , 0.53053636, 0.44925265, 0.41428697, 0.1610422 ,
        0.50392885, 0.69568808, 0.78383881, 0.20740936, 0.43286631,
        0.34061803, 0.        , 0.56810161, 0.39199934, 0.20603376,
        0.49029994, 0.52555187, 0.45057144, 0.48750747, 0.25540342,
        0.04687123, 0.17823575, 0.20221657, 0.        , 0.58930457,
        0.216186  , 0.46658385, 0.47054301, 0.23140711, 0.49190948]))

In [6]:
labels = clusters[0]
labels

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1], dtype=int32)

In [7]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 


In [ ]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


In [8]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data, clust_centers)

(array([[0.67721014, 0.54571798, 0.64738277],
        [0.43592301, 0.31638448, 0.18756801]]),
 0.3454152706463719)

In [10]:
kmeans(data, 2)

(array([[0.76575261, 0.50119159, 0.66914599],
        [0.40370437, 0.37155024, 0.22414973]]),
 0.34445385283461694)