# Intro python data science
## Práctica 03: Paquetes

Vamos a ver:
* Punto 1: Qué son los paquetes y su uso
* Punto 2: Diferencias entre funciones y métodos
* Punto 3: Paquetes básicos en ciencia de datos

# Punto 1:

In [1]:
# Cómo importar un paquete
import numpy

In [4]:
numpy.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# Cómo importar un paquete con acrónimo
import numpy as np

In [6]:
# objeto array de numpy
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Cómo cargar una función específica de un paquete

In [7]:
from numpy import arange

In [8]:
arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Punto 2:

In [ ]:
# Diferencias entre funciones y métodos

In [10]:
a = arange(9)

In [12]:
# que tipo de objeto es A
type(a)

numpy.ndarray

In [13]:
# calculando promedio con función de numpy
np.mean(a)

4.0

In [14]:
# calculando promedio con método de objeto
a.mean()

4.0

In [ ]:
# Haciendo un reshape con funciones y métodos

In [15]:
# transformando arreglo con función de numpy
np.reshape(a, (3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# transformando arreglo con método de objeto
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Gracias!
## Espero que te lleves algo útil de este notebook 😀

Para más videos de programación para ciencia de datos

https://www.youtube.com/c/RafaGonzalezGouveia/

Si quieres realizar alguno de los cursos online de pago, ve a:

https://cursos.gonzalezgouveia.com