## Regresión lineal en Python
### El paquete scikit-learn para regresión lineal y la selección de rasgos

In [2]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('python-ml-course-master/datasets/ads/Advertising.csv')

In [4]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [5]:
x = data[feature_cols]  # Var. predictoras
y = data["Sales"]  # Var. a ser predecida

In [7]:
# Estimar un modelo lineal con el numero deseado de variables predictoras
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(x, y)

In [8]:
# Ver variables seleccionadas (feature_cols) para el modelo
selector.support_

array([ True,  True, False])

In [9]:
# Ver ranking de variables
selector.ranking_

array([1, 1, 2])

In [10]:
# Regresion lineal
from sklearn.linear_model import LinearRegression

In [12]:
x_pred = x[["TV", "Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(x_pred, y)

LinearRegression()

In [14]:
# Intersepcion de ejes
lm.intercept_

2.921099912405138

In [15]:
# Coeficientes
lm.coef_

array([0.04575482, 0.18799423])

In [16]:
# R² ajustado
lm.score(x_pred, y)

0.8971942610828956