# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR  # Support vector regression
import pandas as pd
import numpy as np

### Support Vector Regression
Se basa en buscar la curva, con su respectivo máximo margen, que modele la tendencia de los datos y, según ella, predecir cualquier otro dato en el futuro.

Todo lo que se encuentra fuera del rango es considerado error.

In [4]:
data = pd.read_csv('../python-ml-course-master/datasets/ads/Advertising.csv')
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
feature_cols = ["TV", "Radio", "Newspaper"]

x = data[feature_cols]  # Var. independientes o predictoras
y = data["Sales"]  # Var. dependiente o a ser predecida

In [6]:
# Estimar un modelo lineal con el numero deseado de variables independientes
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(x, y)  # Crea el modelo

In [7]:
# Ver variables seleccionadas (feature_cols) para el modelo
selector.support_

# Resultado: TV y Radio, y Newspaper fue rechazada

array([ True,  True, False])

In [9]:
# Ver ranking de variables
selector.ranking_

array([1, 1, 2])

In [8]:
# Regresion lineal
from sklearn.linear_model import LinearRegression

In [10]:
# Crea modelo de las variables elegidas
x_pred = x[["TV", "Radio"]]
lm = LinearRegression()
lm.fit(x_pred, y)

LinearRegression()

In [11]:
# Intersepcion de ejes
lm.intercept_

2.921099912405138

In [12]:
# Coeficientes
lm.coef_

array([0.04575482, 0.18799423])

In [13]:
# R² ajustado
lm.score(x_pred, y)

0.8971942610828957