# Vectores de NumPy
* np.zeros(n)
* np.ones(n)
* np.full(n, valor)
* np.arange()
* np.random.randint()

In [1]:
import numpy as np

In [ ]:
np_random = np.random.randint(10, size=(5,3))
np_random

array([[8, 9, 6],
       [4, 2, 2],
       [4, 8, 3],
       [2, 7, 5],
       [6, 3, 7]])

In [ ]:
# atributos
np_random.ndim

2

In [ ]:
np_random.shape

(5, 3)

In [ ]:
np_random.size

15

In [ ]:
np_random.dtype

dtype('int32')

In [ ]:
np_random.itemsize

4

In [ ]:
# Concatenacion
# axis=0 concatena por filas y axis=1 concatena por columnas
array_1 = np.random.randint(10, size=5)
array_2 = np.random.randint(10, size=5)

arrays_conc = np.concatenate((array_1, array_2))
arrays_conc

In [ ]:
array_extra = np.array([[10],[20]])
array_extra

array([[10],
       [20]])

In [ ]:
# vstack y hstack para apilar
arrays_apilados_v = np.vstack([array_extra, array_extra])
arrays_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [ ]:
# split, vsplit y hsplit para desarmar o partir
array_partido = np.split(arrays_conc, [4, 6])
array_partido

[array([5, 0, 6, 0]), array([8, 2]), array([8, 5, 7, 2])]

### Calculo con funciones utiles

In [ ]:
calificaciones = np.array([10, 10, 8, 9, 10])

# promedio
calificaciones.mean()

9.4

In [ ]:
# suma
calificaciones.sum()

47

In [ ]:
# maximo
calificaciones.max()

10

In [ ]:
# media
np.median(calificaciones)

10.0

In [ ]:
# desviacion estandar
np.std(calificaciones)

0.7999999999999999